### ISSUE TITLE
"Cleared on" column uses 10-clear date, not first clear

### ISSUE THREAD

**Issue by xephero** [Colbydude/FFXIVProgressionChecker#1]
For example, on your character:

http://ffxiv.voidteam.net/progression?name=Enyl%20Noves&server=Leviathan

It says your BCoB clear was "Fri Feb 27 2015", and yet looking at your achievements:

http://na.finalfantasyxiv.com/lodestone/character/2249861/achievement/category/4/

Your Binds that Tie dates are May 5, 2014, July 6, 2014, and February 27, 2015. "Cleared on" should be the first date, not the last, right?

It looks like this results from the app.js function displayRaidRowByClears, the for loop there sets usedAchievement to the last member of the array, and they're sent in order up in updateDetails, so usedAchievement (then used to set clear_date) ends up being the last achievement.

**Comment by Colbydude** [comment]
Yes, good call! I did initially have it display as:

**First Clear:** Date
**Recent Clear:** Date

I simply forgot to re-add it when I refactored everything. I'm currently on vacation until the middle of the month, but I'll get it re-added ASAP.

**Comment by Colbydude** [comment]
Re-added now! Thanks for noticing!
